
spring:
  profiles:
    include:
      - base-dao
      - base-service

  datasource:
    driver-class-name: org.mariadb.jdbc.Driver

  http:
#    打印请求参数
    log-request-details: true

logging:
  file:
    #    避免以月为单位的 bug
    max-history: 32
